'use strict';

const roomTypes = require('./roomTypes');

const configs = {
  clinics: {
    table: 'clinics',
    fields: ['name', 'whatsapp_number', 'phone', 'timezone', 'default_language', 'is_active'],
    required: ['name', 'timezone', 'default_language'],
    directClinic: true,
    singleton: true,
  },
  branches: {
    table: 'branches',
    fields: ['name', 'city', 'address', 'google_maps_url', 'timezone', 'is_active'],
    required: ['name', 'city', 'timezone'],
    directClinic: true,
  },
  'branch-working-hours': {
    table: 'branch_working_hours',
    fields: ['branch_id', 'day_of_week', 'opens_at', 'closes_at', 'is_closed'],
    required: ['branch_id', 'day_of_week', 'is_closed'],
    scopeJoin: 'JOIN geniusbot.branches scope_branch ON scope_branch.id = r.branch_id',
    scopeColumn: 'scope_branch.clinic_id',
    parentChecks: { branch_id: 'branches' },
    orderBy: 'r.day_of_week ASC',
  },
  'clinic-holidays': {
    table: 'clinic_holidays',
    fields: ['branch_id', 'holiday_date', 'name', 'is_closed', 'opens_at', 'closes_at'],
    required: ['holiday_date', 'is_closed'],
    directClinic: true,
    parentChecks: { branch_id: 'branches' },
    orderBy: 'r.holiday_date DESC',
  },
  doctors: {
    table: 'doctors',
    fields: ['full_name', 'title', 'gender', 'bio', 'is_active'],
    required: ['full_name'],
    directClinic: true,
  },
  specialties: {
    table: 'specialties',
    fields: ['name', 'description', 'is_active'],
    required: ['name'],
    directClinic: true,
  },
  'doctor-specialties': {
    table: 'doctor_specialties',
    fields: ['doctor_id', 'specialty_id'],
    required: ['doctor_id', 'specialty_id'],
    scopeJoin: 'JOIN geniusbot.doctors scope_doctor ON scope_doctor.id = r.doctor_id',
    scopeColumn: 'scope_doctor.clinic_id',
    parentChecks: { doctor_id: 'doctors', specialty_id: 'specialties' },
  },
  'doctor-working-hours': {
    table: 'doctor_working_hours',
    fields: ['doctor_id', 'branch_id', 'day_of_week', 'start_time', 'end_time', 'is_active'],
    required: ['doctor_id', 'branch_id', 'day_of_week', 'start_time', 'end_time'],
    scopeJoin: 'JOIN geniusbot.doctors scope_doctor ON scope_doctor.id = r.doctor_id',
    scopeColumn: 'scope_doctor.clinic_id',
    parentChecks: { doctor_id: 'doctors', branch_id: 'branches' },
    orderBy: 'r.day_of_week ASC, r.start_time ASC',
  },
  'doctor-time-off': {
    table: 'doctor_time_off',
    fields: ['doctor_id', 'start_datetime', 'end_datetime', 'reason'],
    required: ['doctor_id', 'start_datetime', 'end_datetime'],
    scopeJoin: 'JOIN geniusbot.doctors scope_doctor ON scope_doctor.id = r.doctor_id',
    scopeColumn: 'scope_doctor.clinic_id',
    parentChecks: { doctor_id: 'doctors' },
    orderBy: 'r.start_datetime DESC',
  },
  rooms: {
    table: 'rooms',
    fields: ['branch_id', 'room_number', 'room_name', 'room_type', 'is_active'],
    required: ['branch_id', 'room_number', 'room_name', 'room_type'],
    scopeJoin: 'JOIN geniusbot.branches scope_branch ON scope_branch.id = r.branch_id',
    scopeColumn: 'scope_branch.clinic_id',
    parentChecks: { branch_id: 'branches' },
    roomTypes,
  },
  'room-time-off': {
    table: 'room_time_off',
    fields: ['room_id', 'start_datetime', 'end_datetime', 'reason'],
    required: ['room_id', 'start_datetime', 'end_datetime'],
    scopeJoin: 'JOIN geniusbot.rooms scope_room ON scope_room.id = r.room_id JOIN geniusbot.branches scope_branch ON scope_branch.id = scope_room.branch_id',
    scopeColumn: 'scope_branch.clinic_id',
    parentChecks: { room_id: 'rooms' },
    orderBy: 'r.start_datetime DESC',
  },
  services: {
    table: 'services',
    fields: ['specialty_id', 'name', 'aliases', 'description', 'duration_minutes', 'requires_doctor', 'requires_room', 'is_booking_enabled', 'is_active', 'display_order'],
    required: ['name', 'duration_minutes'],
    directClinic: true,
    parentChecks: { specialty_id: 'specialties' },
    orderBy: 'r.display_order ASC, r.name ASC',
  },
  'service-pre-questions': {
    table: 'service_pre_questions',
    fields: ['service_id', 'question_text', 'answer_type', 'blocking_answer', 'is_active', 'display_order'],
    required: ['service_id', 'question_text', 'answer_type'],
    scopeJoin: 'JOIN geniusbot.services scope_service ON scope_service.id = r.service_id',
    scopeColumn: 'scope_service.clinic_id',
    parentChecks: { service_id: 'services' },
    orderBy: 'r.display_order ASC',
  },
  'payment-methods': {
    table: 'payment_methods',
    fields: ['name', 'code', 'is_active'],
    required: ['name', 'code'],
    directClinic: true,
  },
  'insurance-companies': {
    table: 'insurance_companies',
    fields: ['name', 'is_active'],
    required: ['name'],
    directClinic: true,
  },
  'insurance-classes': {
    table: 'insurance_classes',
    fields: ['insurance_company_id', 'class_name', 'is_accepted'],
    required: ['insurance_company_id', 'class_name'],
    scopeJoin: 'JOIN geniusbot.insurance_companies scope_company ON scope_company.id = r.insurance_company_id',
    scopeColumn: 'scope_company.clinic_id',
    parentChecks: { insurance_company_id: 'insurance_companies' },
  },
};

module.exports = Object.freeze(configs);
