'use strict';

const { ROLES, isValidRole } = require('./roles');

const PERMISSIONS = Object.freeze({
  // Platform
  PLATFORM_VIEW: 'platform:view',
  PLATFORM_MANAGE_CLINICS: 'platform:manage_clinics',
  PLATFORM_MANAGE_STAFF: 'platform:manage_staff',

  // Clinic
  CLINIC_VIEW: 'clinic:view',
  CLINIC_UPDATE: 'clinic:update',
  CLINIC_TRANSFER_OWNERSHIP: 'clinic:transfer_ownership',

  // Branches
  BRANCH_VIEW: 'branch:view',
  BRANCH_CREATE: 'branch:create',
  BRANCH_UPDATE: 'branch:update',
  BRANCH_DELETE: 'branch:delete',

  // Services
  SERVICE_VIEW: 'service:view',
  SERVICE_CREATE: 'service:create',
  SERVICE_UPDATE: 'service:update',
  SERVICE_DELETE: 'service:delete',

  // Doctors
  DOCTOR_VIEW: 'doctor:view',
  DOCTOR_CREATE: 'doctor:create',
  DOCTOR_UPDATE: 'doctor:update',
  DOCTOR_DELETE: 'doctor:delete',

  // Rooms
  ROOM_VIEW: 'room:view',
  ROOM_CREATE: 'room:create',
  ROOM_UPDATE: 'room:update',
  ROOM_DELETE: 'room:delete',

  // Staff
  STAFF_VIEW: 'staff:view',
  STAFF_CREATE: 'staff:create',
  STAFF_UPDATE: 'staff:update',
  STAFF_DISABLE: 'staff:disable',
  STAFF_CHANGE_ROLE: 'staff:change_role',

  // Patients
  PATIENT_VIEW: 'patient:view',
  PATIENT_CREATE: 'patient:create',
  PATIENT_UPDATE: 'patient:update',

  // Appointments
  APPOINTMENT_VIEW: 'appointment:view',
  APPOINTMENT_CREATE: 'appointment:create',
  APPOINTMENT_UPDATE: 'appointment:update',
  APPOINTMENT_CONFIRM: 'appointment:confirm',
  APPOINTMENT_CANCEL: 'appointment:cancel',
  APPOINTMENT_COMPLETE: 'appointment:complete',
  APPOINTMENT_NO_SHOW: 'appointment:no_show',
  APPOINTMENT_RESCHEDULE: 'appointment:reschedule',

  // Dashboard
  DASHBOARD_VIEW: 'dashboard:view',

  // Conversations
  CONVERSATION_VIEW: 'conversation:view',
  CONVERSATION_REPLY: 'conversation:reply',
  CONVERSATION_ASSIGN: 'conversation:assign',
  CONVERSATION_CLOSE: 'conversation:close',

  // Financial
  FINANCIAL_VIEW: 'financial:view',
  FINANCIAL_CREATE: 'financial:create',
  FINANCIAL_UPDATE: 'financial:update',
  FINANCIAL_REFUND: 'financial:refund',

  // AI
  AI_SETTINGS_VIEW: 'ai_settings:view',
  AI_SETTINGS_UPDATE: 'ai_settings:update',

  // Notifications
  NOTIFICATION_VIEW: 'notification:view',
  NOTIFICATION_SEND: 'notification:send',
  NOTIFICATION_SETTINGS_UPDATE: 'notification_settings:update',

  // Reports
  REPORT_VIEW_OPERATIONAL: 'report:view_operational',
  REPORT_VIEW_FINANCIAL: 'report:view_financial',
  REPORT_EXPORT: 'report:export',

  // Integrations
  INTEGRATION_VIEW: 'integration:view',
  INTEGRATION_UPDATE: 'integration:update',
});

const ALL_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.PLATFORM_ADMIN]: ALL_PERMISSIONS,

  [ROLES.OWNER]: Object.freeze([
    PERMISSIONS.CLINIC_VIEW,
    PERMISSIONS.CLINIC_UPDATE,
    PERMISSIONS.CLINIC_TRANSFER_OWNERSHIP,

    PERMISSIONS.BRANCH_VIEW,
    PERMISSIONS.BRANCH_CREATE,
    PERMISSIONS.BRANCH_UPDATE,
    PERMISSIONS.BRANCH_DELETE,

    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_UPDATE,
    PERMISSIONS.SERVICE_DELETE,

    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.DOCTOR_CREATE,
    PERMISSIONS.DOCTOR_UPDATE,
    PERMISSIONS.DOCTOR_DELETE,

    PERMISSIONS.ROOM_VIEW,
    PERMISSIONS.ROOM_CREATE,
    PERMISSIONS.ROOM_UPDATE,
    PERMISSIONS.ROOM_DELETE,

    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_DISABLE,
    PERMISSIONS.STAFF_CHANGE_ROLE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CONFIRM,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    PERMISSIONS.APPOINTMENT_NO_SHOW,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,

    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CONVERSATION_VIEW,
    PERMISSIONS.CONVERSATION_REPLY,
    PERMISSIONS.CONVERSATION_ASSIGN,
    PERMISSIONS.CONVERSATION_CLOSE,

    PERMISSIONS.FINANCIAL_VIEW,
    PERMISSIONS.FINANCIAL_CREATE,
    PERMISSIONS.FINANCIAL_UPDATE,
    PERMISSIONS.FINANCIAL_REFUND,

    PERMISSIONS.AI_SETTINGS_VIEW,
    PERMISSIONS.AI_SETTINGS_UPDATE,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.NOTIFICATION_SETTINGS_UPDATE,

    PERMISSIONS.REPORT_VIEW_OPERATIONAL,
    PERMISSIONS.REPORT_VIEW_FINANCIAL,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.INTEGRATION_VIEW,
    PERMISSIONS.INTEGRATION_UPDATE,
  ]),

  [ROLES.CLINIC_ADMIN]: Object.freeze([
    PERMISSIONS.CLINIC_VIEW,
    PERMISSIONS.CLINIC_UPDATE,

    PERMISSIONS.BRANCH_VIEW,
    PERMISSIONS.BRANCH_CREATE,
    PERMISSIONS.BRANCH_UPDATE,
    PERMISSIONS.BRANCH_DELETE,

    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_UPDATE,
    PERMISSIONS.SERVICE_DELETE,

    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.DOCTOR_CREATE,
    PERMISSIONS.DOCTOR_UPDATE,
    PERMISSIONS.DOCTOR_DELETE,

    PERMISSIONS.ROOM_VIEW,
    PERMISSIONS.ROOM_CREATE,
    PERMISSIONS.ROOM_UPDATE,
    PERMISSIONS.ROOM_DELETE,

    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CONFIRM,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    PERMISSIONS.APPOINTMENT_NO_SHOW,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,

    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CONVERSATION_VIEW,
    PERMISSIONS.CONVERSATION_REPLY,
    PERMISSIONS.CONVERSATION_ASSIGN,
    PERMISSIONS.CONVERSATION_CLOSE,

    PERMISSIONS.FINANCIAL_VIEW,
    PERMISSIONS.FINANCIAL_CREATE,
    PERMISSIONS.FINANCIAL_UPDATE,

    PERMISSIONS.AI_SETTINGS_VIEW,
    PERMISSIONS.AI_SETTINGS_UPDATE,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.NOTIFICATION_SETTINGS_UPDATE,

    PERMISSIONS.REPORT_VIEW_OPERATIONAL,
    PERMISSIONS.REPORT_VIEW_FINANCIAL,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.INTEGRATION_VIEW,
    PERMISSIONS.INTEGRATION_UPDATE,
  ]),

  [ROLES.BRANCH_MANAGER]: Object.freeze([
    PERMISSIONS.CLINIC_VIEW,

    PERMISSIONS.BRANCH_VIEW,
    PERMISSIONS.BRANCH_UPDATE,

    PERMISSIONS.SERVICE_VIEW,

    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.ROOM_VIEW,

    PERMISSIONS.STAFF_VIEW,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CONFIRM,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    PERMISSIONS.APPOINTMENT_NO_SHOW,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,

    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CONVERSATION_VIEW,
    PERMISSIONS.CONVERSATION_REPLY,
    PERMISSIONS.CONVERSATION_ASSIGN,
    PERMISSIONS.CONVERSATION_CLOSE,

    PERMISSIONS.FINANCIAL_VIEW,
    PERMISSIONS.FINANCIAL_CREATE,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,

    PERMISSIONS.REPORT_VIEW_OPERATIONAL,
  ]),

  [ROLES.RECEPTIONIST]: Object.freeze([
    PERMISSIONS.CLINIC_VIEW,
    PERMISSIONS.BRANCH_VIEW,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.ROOM_VIEW,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CONFIRM,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    PERMISSIONS.APPOINTMENT_NO_SHOW,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,

    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CONVERSATION_VIEW,
    PERMISSIONS.CONVERSATION_REPLY,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,
  ]),

  [ROLES.DOCTOR]: Object.freeze([
    PERMISSIONS.CLINIC_VIEW,
    PERMISSIONS.BRANCH_VIEW,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.ROOM_VIEW,

    PERMISSIONS.PATIENT_VIEW,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    PERMISSIONS.APPOINTMENT_NO_SHOW,

    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CONVERSATION_VIEW,
    PERMISSIONS.CONVERSATION_REPLY,
  ]),
});

function isValidPermission(permission) {
  return (
    typeof permission === 'string' &&
    ALL_PERMISSIONS.includes(permission)
  );
}

function assertValidPermission(permission) {
  if (!isValidPermission(permission)) {
    throw new TypeError(
      `Invalid permission: ${String(permission)}`
    );
  }

  return permission;
}

function getPermissions(role) {
  if (!isValidRole(role)) {
    return [];
  }

  return ROLE_PERMISSIONS[role] || [];
}

function hasPermission(role, permission) {
  if (!isValidPermission(permission)) {
    return false;
  }

  return getPermissions(role).includes(permission);
}

function hasAnyPermission(role, permissions) {
  if (!Array.isArray(permissions) || permissions.length === 0) {
    return false;
  }

  return permissions.some((permission) =>
    hasPermission(role, permission)
  );
}

function hasAllPermissions(role, permissions) {
  if (!Array.isArray(permissions) || permissions.length === 0) {
    return false;
  }

  return permissions.every((permission) =>
    hasPermission(role, permission)
  );
}

module.exports = {
  PERMISSIONS,
  ALL_PERMISSIONS,
  ROLE_PERMISSIONS,
  isValidPermission,
  assertValidPermission,
  getPermissions,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
};